name: $(SourceBranchName)-$(Rev:.r)

variables:
  EXEC_CONTAINER: false

trigger:
  batch: true
  paths:
    exclude:
      - cmd/pipehub/pipehub.sample.hcl
      - misc/docker/build/entrypoint.sh
      - misc/docker/ci/tools.json
      - .gitignore
      - .goreleaser.yml
      - changelog.md
      - license
      - readme.md

jobs:
  - job: job1
    container: pipehub/ci:1
    pool:
      vmImage: Ubuntu 16.04
    displayName: 'Quality'
    steps:
      - script: go build -mod readonly -o bin/pipehub/pipehub cmd/pipehub/*.go
      - script: make go-test
      - script: make go-linter
      - script: make go-linter-vendor
      - script: make docker-linter
  # - job: job2
  #   container: pipehub/ci:1
  #   pool:
  #     vmImage: Ubuntu 16.04
  #   displayName: 'Test'
  #   steps:
  #     - script: make go-test
  # - job: job3
  #   container: pipehub/ci:1
  #   pool:
  #     vmImage: Ubuntu 16.04
  #   displayName: 'Linter'
  #   steps:
  #     - script: make go-linter
  # - job: job4
  #   container: pipehub/ci:1
  #   pool:
  #     vmImage: Ubuntu 16.04
  #   displayName: 'Linter Vendor'
  #   steps:
  #     - script: make go-linter-vendor
  # - job: job5
  #   container: pipehub/ci:1
  #   pool:
  #     vmImage: Ubuntu 16.04
  #   displayName: 'Linter'
  #   steps:
  #     - script: make docker-linter
